#Operates in London
environment            = "development"
region                 = "eu-west-2"
ami_id                 = "ami-0be057a22c63962cb"
instance-type          = "t2.micro"
pem-key                = "recipe-generator-keypair" 	
subnet_id              = "subnet-084bd0c21d636485e"
vpc_security_group_ids = ["sg-a005e8c0"]
volume                 = "16"
value                  = "2"